# Generated by Django 5.2.16 on 2026-07-31 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('role', models.CharField(choices=[('patient', 'patient'), ('doctor', 'doctor')], default='patient', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('occupation', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.FloatField(default=0)),
                ('protein_pct', models.FloatField(default=0)),
                ('carbs_pct', models.FloatField(default=0)),
                ('fat_pct', models.FloatField(default=0)),
                ('plan_notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clinic.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('bmi', models.FloatField(default=0)),
                ('bmi_class', models.CharField(blank=True, default='', max_length=20)),
                ('waist', models.FloatField(default=0)),
                ('hip', models.FloatField(default=0)),
                ('whr', models.FloatField(default=0)),
                ('medical_history', models.JSONField(blank=True, default=list)),
                ('medical_other', models.CharField(blank=True, default='', max_length=255)),
                ('surgeries', models.CharField(blank=True, default='', max_length=255)),
                ('food_allergy', models.CharField(blank=True, default='', max_length=255)),
                ('digestive_issues', models.JSONField(blank=True, default=list)),
                ('current_medications', models.CharField(blank=True, default='', max_length=255)),
                ('weight_loss_meds', models.JSONField(blank=True, default=list)),
                ('weight_loss_meds_other', models.CharField(blank=True, default='', max_length=255)),
                ('supplements', models.CharField(blank=True, default='', max_length=255)),
                ('activity_level', models.CharField(blank=True, default='', max_length=20)),
                ('sport_type', models.CharField(blank=True, default='', max_length=100)),
                ('sport_days_per_week', models.IntegerField(default=0)),
                ('sleep_hours', models.FloatField(default=0)),
                ('sleep_quality', models.CharField(blank=True, default='', max_length=20)),
                ('stress_level', models.CharField(blank=True, default='', max_length=20)),
                ('appetite', models.CharField(blank=True, default='', max_length=20)),
                ('night_hunger', models.BooleanField(default=False)),
                ('sugar_craving', models.BooleanField(default=False)),
                ('insulin_resistance', models.BooleanField(default=False)),
                ('hormonal_symptoms', models.BooleanField(default=False)),
                ('meals_per_day', models.IntegerField(default=0)),
                ('snack', models.BooleanField(default=False)),
                ('eating_type', models.CharField(blank=True, default='', max_length=20)),
                ('favorite_foods', models.CharField(blank=True, default='', max_length=255)),
                ('disliked_foods', models.CharField(blank=True, default='', max_length=255)),
                ('water_liters', models.FloatField(default=0)),
                ('coffee_per_day', models.IntegerField(default=0)),
                ('sugar_intake', models.CharField(blank=True, default='', max_length=20)),
                ('goal_type', models.CharField(blank=True, default='', max_length=30)),
                ('current_weight', models.FloatField(default=0)),
                ('target_weight', models.FloatField(default=0)),
                ('goal_duration', models.CharField(blank=True, default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(default=0)),
                ('bmi', models.FloatField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('commitment', models.CharField(blank=True, default='', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='clinic.patient')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
