# Generated by Django 5.2.16 on 2026-07-31 22:03

import django.utils.timezone
from django.db import migrations, models


def blank_phones_to_null(apps, schema_editor):
    """Existing rows with phone="" would violate the new unique constraint
    once more than one of them shares the same empty string. Convert blanks
    to NULL first — SQLite/Postgres both allow multiple NULLs in a unique
    column, so this is safe and non-destructive."""
    User = apps.get_model("clinic", "User")
    User.objects.filter(phone="").update(phone=None)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        # Step 1: allow NULL first (no uniqueness yet) so the data migration
        # below can null out blank values without violating NOT NULL.
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RunPython(blank_phones_to_null, noop_reverse),
        # Step 2: now enforce uniqueness — safe because duplicate blanks are NULL now.
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
