# Generated by Django 5.2.16 on 2026-08-02 05:00

from django.db import migrations, models


def split_existing_names(apps, schema_editor):
    """Best-effort split of the existing single `full_name` string into
    name_first / name_father / name_grandfather for already-registered patients.
    Doctor accounts are untouched — this only walks Patient rows."""
    Patient = apps.get_model("clinic", "Patient")
    for patient in Patient.objects.select_related("user").all():
        full_name = (patient.user.full_name or "").strip()
        parts = full_name.split()
        patient.name_first = parts[0] if len(parts) > 0 else ""
        patient.name_father = parts[1] if len(parts) > 1 else ""
        patient.name_grandfather = " ".join(parts[2:]) if len(parts) > 2 else ""
        patient.save(update_fields=["name_first", "name_father", "name_grandfather"])


def noop_reverse_names(apps, schema_editor):
    pass


def convert_height_and_recompute(apps, schema_editor):
    """Historical `height` values were stored in centimeters (e.g. 170).
    Convert them to meters (1.70) and recompute everything that's derived
    from height/activity so old records stay internally consistent with the
    new automatic formulas."""
    Assessment = apps.get_model("clinic", "Assessment")

    ACTIVITY_MULTIPLIERS = {"قليل": 1.375, "متوسط": 1.55, "عالي": 1.725}

    def bmi_class(bmi):
        if bmi < 18.5:
            return "نقص وزن"
        elif bmi < 25:
            return "طبيعي"
        elif bmi < 30:
            return "زيادة وزن"
        return "سمنة"

    def whr_class(whr, gender):
        if not whr:
            return ""
        if gender == "أنثى":
            if whr < 0.80:
                return "طبيعي"
            elif whr < 0.85:
                return "خطر متوسط"
            return "خطر عالي"
        if whr < 0.90:
            return "طبيعي"
        elif whr < 1.0:
            return "خطر متوسط"
        return "خطر عالي"

    def activity_level(days):
        try:
            days = int(days or 0)
        except (TypeError, ValueError):
            days = 0
        if days <= 1:
            return "قليل"
        elif days <= 4:
            return "متوسط"
        return "عالي"

    for a in Assessment.objects.select_related("patient").all():
        changed_fields = []

        # Heuristic: any stored height > 10 is still in centimeters (real
        # heights in meters are always well under 10). Convert once.
        if a.height and a.height > 10:
            a.height = round(a.height / 100, 2)
            changed_fields.append("height")

        if a.weight and a.height:
            a.bmi = round(a.weight / (a.height * a.height), 1)
            a.bmi_class = bmi_class(a.bmi)
            changed_fields += ["bmi", "bmi_class"]

        gender = a.patient.gender if a.patient_id else ""
        a.whr_class = whr_class(a.whr, gender)
        changed_fields.append("whr_class")

        a.activity_level = activity_level(a.sport_days_per_week)
        changed_fields.append("activity_level")

        if changed_fields:
            a.save(update_fields=list(dict.fromkeys(changed_fields)))


def noop_reverse_height(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_phone_unique_and_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='whr_class',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_father',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_first',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_grandfather',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='activity_level',
            field=models.CharField(blank=True, default='', help_text='يُحسب تلقائياً من عدد أيام الرياضة الأسبوعية، وليس إدخالاً يدوياً', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='height',
            field=models.FloatField(default=0, help_text='بالمتر، مثال: 1.70'),
        ),
        migrations.RunPython(split_existing_names, noop_reverse_names),
        migrations.RunPython(convert_height_and_recompute, noop_reverse_height),
    ]
