# Generated by Django 5.2.16 on 2026-08-02 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_assessment_whr_class_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insulin_resistance_value', models.FloatField(default=0)),
                ('lab_results', models.JSONField(blank=True, default=dict)),
                ('diet_type', models.CharField(blank=True, default='', max_length=150)),
                ('diet_details', models.TextField(blank=True, default='')),
                ('diet_calories', models.FloatField(default=0)),
                ('treatments', models.JSONField(blank=True, default=list)),
                ('followup_interval_value', models.IntegerField(default=0)),
                ('followup_interval_unit', models.CharField(blank=True, default='', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='clinic.patient')),
            ],
        ),
    ]
