# Generated by Django 5.2.16 on 2026-08-02 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_followuprecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MounjaroDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(default=0)),
                ('dose_mg', models.FloatField(choices=[(2.5, '2.5 ملغم'), (5.0, '5 ملغم'), (7.5, '7.5 ملغم'), (10.0, '10 ملغم'), (12.5, '12.5 ملغم'), (15.0, '15 ملغم')], default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounjaro_doses', to='clinic.patient')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
