# Generated by Django 5.2.16 on 2026-08-06 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('group', models.CharField(blank=True, default='', max_length=150)),
                ('type', models.CharField(choices=[('دواء', 'دواء'), ('مكمل غذائي', 'مكمل غذائي')], default='دواء', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'name'],
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, default='', max_length=200)),
                ('brand_name', models.CharField(blank=True, default='', max_length=200)),
                ('medication_type', models.CharField(choices=[('دواء', 'دواء'), ('مكمل غذائي', 'مكمل غذائي')], default='دواء', max_length=20)),
                ('dosage_form', models.CharField(blank=True, default='', help_text='مثال: أقراص، حقنة، شراب', max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_medications', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='clinic.medicationcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_value', models.CharField(max_length=50)),
                ('dose_unit', models.CharField(blank=True, default='', max_length=20)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='clinic.medication')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateTimeField(auto_now_add=True)),
                ('general_notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinic.patient')),
            ],
            options={
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_medication_name', models.CharField(blank=True, default='', max_length=200)),
                ('custom_dose', models.CharField(blank=True, default='', max_length=100)),
                ('route', models.CharField(blank=True, default='', max_length=30)),
                ('frequency', models.CharField(blank=True, default='', max_length=50)),
                ('timing', models.CharField(blank=True, default='', max_length=50)),
                ('duration_value', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, default='', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('instructions', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('treatment_status', models.CharField(choices=[('مستمر', 'مستمر'), ('مكتمل', 'مكتمل'), ('متوقف', 'متوقف'), ('تم تغيير الجرعة', 'تم تغيير الجرعة')], default='مستمر', max_length=30)),
                ('stop_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='clinic.medication')),
                ('medication_dose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='clinic.medicationdose')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
