# Generated by Django 5.2.16 on 2026-08-09, hand-edited to preserve existing
# NutritionPlan.daily_calories data (renamed to calorie_target) across the
# schema change — see _capture_old_calorie_targets / _apply_calorie_targets.

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

_old_calorie_targets = {}


def _capture_old_calorie_targets(apps, schema_editor):
    NutritionPlan = apps.get_model("clinic", "NutritionPlan")
    for plan in NutritionPlan.objects.all():
        _old_calorie_targets[plan.id] = plan.daily_calories


def _apply_calorie_targets(apps, schema_editor):
    NutritionPlan = apps.get_model("clinic", "NutritionPlan")
    Meal = apps.get_model("clinic", "Meal")
    for plan_id, daily_calories in _old_calorie_targets.items():
        NutritionPlan.objects.filter(id=plan_id).update(calorie_target=daily_calories or 0)
    # Pre-existing plans (created under the old single-record shape) have no
    # meal slots yet — give them the standard 5 so they work in the new
    # meal-builder UI right away, same as any newly created plan.
    for meal_type, order in [("فطور", 0), ("سناك1", 1), ("غداء", 2), ("سناك2", 3), ("عشاء", 4)]:
        for plan_id in _old_calorie_targets:
            Meal.objects.get_or_create(plan_id=plan_id, meal_type=meal_type, defaults={"order": order})


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_medicationcategory_medication_medicationdose_and_more'),
    ]

    operations = [
        migrations.RunPython(_capture_old_calorie_targets, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='nutritionplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='daily_calories',
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='activity_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='bmr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='calorie_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 9, 18, 35, 4, 913905, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='duration_unit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='duration_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='eating_disorder_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='is_lactating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='medically_unstable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='clinic.nutritionplan'),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='patient_notes',
            field=models.TextField(blank=True, default='', help_text='ملاحظات وتعليمات تظهر للمريض (ماء، نشاط، إلخ)'),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='protein_grams_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='special_pathway_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='status',
            field=models.CharField(choices=[('Draft', 'مسودة'), ('Active', 'مفعّلة'), ('Archived', 'مؤرشفة')], default='Draft', max_length=10),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='target_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='tdee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='treatment_objective',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_plans_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='plan_notes',
            field=models.TextField(blank=True, default='', help_text='ملاحظات للطبيب فقط — لا تظهر للمريض'),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(choices=[('غم', 'غم'), ('مل', 'مل'), ('قطعة', 'قطعة'), ('كوب', 'كوب'), ('ملعقة كبيرة', 'ملعقة كبيرة'), ('ملعقة صغيرة', 'ملعقة صغيرة')], default='غم', max_length=20)),
                ('calories_per_unit', models.FloatField(default=0)),
                ('protein_per_unit', models.FloatField(default=0)),
                ('carbs_per_unit', models.FloatField(default=0)),
                ('fat_per_unit', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('فطور', 'فطور'), ('سناك1', 'سناك 1'), ('غداء', 'غداء'), ('سناك2', 'سناك 2'), ('عشاء', 'عشاء')], max_length=20)),
                ('time', models.TimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='clinic.nutritionplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_food_name', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, default='غم', max_length=20)),
                ('food_state', models.CharField(blank=True, default='', max_length=30)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('alternative_text', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.CharField(blank=True, default='', max_length=255)),
                ('patient_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_items', to='clinic.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.meal')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(_apply_calorie_targets, migrations.RunPython.noop),
    ]
