# Generated by Django 5.2.16 on 2026-08-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_nutrition_plan_versioning_and_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, choices=[('فطور عراقي', 'فطور عراقي'), ('خبز', 'خبز'), ('بيض', 'بيض'), ('ألبان', 'ألبان'), ('بقوليات', 'بقوليات'), ('خضروات', 'خضروات'), ('فواكه', 'فواكه'), ('إضافات', 'إضافات'), ('مشروبات', 'مشروبات')], default='', max_length=20),
        ),
    ]
