# Generated by Django 5.2.16 on 2026-08-10 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_alter_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('discount_pct', models.FloatField(default=0)),
                ('discount_reason_key', models.CharField(blank=True, choices=[('الأصدقاء', 'الأصدقاء'), ('الأقارب', 'الأقارب'), ('الطلبة', 'الطلبة'), ('ذوو الإعاقة', 'ذوو الإعاقة'), ('سبب مخصص', 'سبب مخصص')], default='', max_length=20)),
                ('discount_reason_custom', models.CharField(blank=True, default='', max_length=200)),
                ('payment_method', models.CharField(blank=True, choices=[('نقدا', 'نقدا (Cash)'), ('Master Qi Card', 'Master Qi Card')], default='', max_length=20)),
                ('amount_paid', models.FloatField(default=0)),
                ('payment_status', models.CharField(choices=[('غير مدفوعة', 'غير مدفوعة'), ('مدفوعة جزئيا', 'مدفوعة جزئيا'), ('مدفوعة', 'مدفوعة'), ('ملغاة', 'ملغاة'), ('مستردة', 'مستردة')], default='غير مدفوعة', max_length=20)),
                ('cancel_refund_reason', models.TextField(blank=True, default='')),
                ('is_locked', models.BooleanField(default=False, help_text='يُقفل تلقائياً عند تسجيل الدفع الكامل')),
                ('last_correction_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('discount_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_approved', to=settings.AUTH_USER_MODEL)),
                ('discount_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_entered', to=settings.AUTH_USER_MODEL)),
                ('last_correction_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_corrections', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clinic.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='clinic.invoice')),
            ],
            options={
                'verbose_name_plural': 'Audit log entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.PositiveIntegerField(default=0, help_text='بالدينار العراقي (IQD)')),
                ('pricing_note', models.CharField(blank=True, default='', help_text='مثال: لكل جلسة، لكل إبرة', max_length=200)),
                ('has_variants', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('price_updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='clinic.service')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_free_followup', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.invoice')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='clinic.service')),
                ('service_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='clinic.servicevariant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
