# Generated by Django 5.2.16 on 2026-08-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_invoice_auditlogentry_service_servicevariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_first_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
