# Generated by Django 5.2.16 on 2026-08-18 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_patient_doctor_first_opened_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MounjaroCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateTimeField()),
                ('original_weight', models.FloatField()),
                ('original_dose_mg', models.FloatField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounjaro_corrections', to='clinic.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
