# Generated by Django 5.2.16 on 2026-08-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0022_mounjarocorrectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('ckb', 'کوردیی ناوەندی')], default='ar', max_length=5),
        ),
    ]
