# Generated by Django 5.2.16 on 2026-08-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0024_alter_mounjarocorrectionlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mounjarodose',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='ozempicdose',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='ozempicdose',
            name='pen_strength',
            field=models.CharField(blank=True, choices=[('2/1.5', '٢ ملغم / ١.٥ مل (لجرعة ٠.٢٥ أو ٠.٥ ملغم)'), ('4/3', '٤ ملغم / ٣ مل (لجرعة ١ ملغم)'), ('8/3', '٨ ملغم / ٣ مل (لجرعة ٢ ملغم)')], default='', max_length=10),
        ),
    ]
