# Generated by Django 5.2.16 on 2026-08-29 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0025_alter_mounjarodose_options_alter_ozempicdose_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionAIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('model', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('successful', 'نجح'), ('failed', 'فشل'), ('applied', 'تم التطبيق')], max_length=12)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.FloatField(blank=True, null=True)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('error_category', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_ai_requests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_ai_requests', to='clinic.patient')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='clinic.nutritionplan')),
            ],
            options={
                'verbose_name_plural': 'Nutrition AI request logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
