# Generated by Django 5.2.16 on 2026-08-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_nutritionairequestlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, default='', help_text='مفتاح OpenAI API. اتركه فارغاً لاستخدام متغير البيئة OPENAI_API_KEY على الخادم بدلاً منه.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الذكاء الاصطناعي',
                'verbose_name_plural': 'إعدادات الذكاء الاصطناعي',
            },
        ),
    ]
