# Generated by Django 5.2.16 on 2026-08-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0027_nutritionaisettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['day_number', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='meal',
            name='day_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
