# Generated by Django 5.2.16 on 2026-09-01 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0028_alter_meal_options_meal_day_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionaisettings',
            name='default_snack1_food',
            field=models.ForeignKey(blank=True, help_text='الصنف الافتراضي لوجبة سناك 1 — يُضاف تلقائياً لكل خطة جديدة. اتركه فارغاً لعدم إضافة أي شيء تلقائياً.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clinic.food'),
        ),
        migrations.AddField(
            model_name='nutritionaisettings',
            name='default_snack1_quantity',
            field=models.FloatField(blank=True, help_text='الكمية (بوحدة الصنف نفسها)', null=True),
        ),
        migrations.AddField(
            model_name='nutritionaisettings',
            name='default_snack2_food',
            field=models.ForeignKey(blank=True, help_text='الصنف الافتراضي لوجبة سناك 2 — يُضاف تلقائياً لكل خطة جديدة. اتركه فارغاً لعدم إضافة أي شيء تلقائياً.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clinic.food'),
        ),
        migrations.AddField(
            model_name='nutritionaisettings',
            name='default_snack2_quantity',
            field=models.FloatField(blank=True, help_text='الكمية (بوحدة الصنف نفسها)', null=True),
        ),
    ]
