# Generated by Django 5.2.16 on 2026-09-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0029_nutritionaisettings_default_snack1_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionaisettings',
            name='default_snack1_quantity',
        ),
        migrations.RemoveField(
            model_name='nutritionaisettings',
            name='default_snack2_quantity',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='is_auto_snack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutritionaisettings',
            name='default_snack1_calorie_pct',
            field=models.FloatField(blank=True, help_text='نسبة سناك 1 من مجموع السعرات اليومية المستهدفة للخطة (مثال: أدخل 5 لتعني 5%) — الكمية تُحسب تلقائياً لكل مريضة حسب هدفها الخاص.', null=True),
        ),
        migrations.AddField(
            model_name='nutritionaisettings',
            name='default_snack2_calorie_pct',
            field=models.FloatField(blank=True, help_text='نسبة سناك 2 من مجموع السعرات اليومية المستهدفة للخطة (مثال: أدخل 5 لتعني 5%) — الكمية تُحسب تلقائياً لكل مريضة حسب هدفها الخاص.', null=True),
        ),
    ]
