# Generated by Django 5.2.16 on 2026-08-24 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0023_patient_preferred_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('appointment', 'تذكير بموعد (Appointment Reminder)'), ('dose', 'تذكير بجرعة (Dose Reminder)'), ('followup', 'تذكير بمراجعة (Follow-up Reminder)'), ('visit', 'تذكير بزيارة (Visit Reminder)'), ('test', 'تذكير بفحص (Test Reminder)'), ('custom_admin', 'إشعار إداري (Custom Administrative Reminder)')], max_length=20)),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('ckb', 'کوردیی ناوەندی')], max_length=5)),
                ('display_name', models.CharField(help_text='اسم داخلي يظهر للسكرتيرة، مثال: تذكير موعد زيارة - عربي', max_length=150)),
                ('meta_template_name', models.CharField(help_text='اسم القالب كما هو مسجل في Meta، مثال: appointment_reminder_ar', max_length=150)),
                ('meta_template_language_code', models.CharField(default='ar', help_text='رمز اللغة في Meta، مثال: ar أو en_US أو ckb — يجب أن يطابق تسجيل القالب تماماً', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(help_text='نص القالب المعتمد حرفياً من Meta، مع بقاء {{1}} {{2}} ... كما هي')),
                ('status', models.CharField(choices=[('approved', 'معتمد (Approved)'), ('pending', 'قيد المراجعة (Pending)'), ('rejected', 'مرفوض (Rejected)'), ('disabled', 'معطّل (Disabled)')], default='pending', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='تعطيل مؤقت من الإدارة — منفصل عن حالة الاعتماد لدى Meta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['reminder_type', 'language'],
                'unique_together': {('reminder_type', 'language')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('ckb', 'کوردیی ناوەندی')], max_length=5)),
                ('reminder_type', models.CharField(choices=[('appointment', 'تذكير بموعد (Appointment Reminder)'), ('dose', 'تذكير بجرعة (Dose Reminder)'), ('followup', 'تذكير بمراجعة (Follow-up Reminder)'), ('visit', 'تذكير بزيارة (Visit Reminder)'), ('test', 'تذكير بفحص (Test Reminder)'), ('custom_admin', 'إشعار إداري (Custom Administrative Reminder)')], max_length=20)),
                ('message_variables', models.JSONField(blank=True, default=dict)),
                ('additional_note', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد الإرسال'), ('sending', 'جارِ الإرسال'), ('sent', 'تم الإرسال'), ('delivered', 'تم التوصيل'), ('read', 'تمت القراءة'), ('failed', 'فشل الإرسال'), ('cancelled', 'أُلغي')], default='draft', max_length=10)),
                ('wa_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_reminders', to='clinic.assessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders_created', to=settings.AUTH_USER_MODEL)),
                ('dose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_reminders', to='clinic.mounjarodose')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_reminders', to='clinic.patient')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders_sent', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='reminders.remindertemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppReminderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'تم الإنشاء'), ('confirmed', 'تم التأكيد'), ('sent', 'تم الإرسال'), ('delivered', 'تم التوصيل'), ('read', 'تمت القراءة'), ('failed', 'فشل'), ('cancelled', 'أُلغي')], max_length=12)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reminders.whatsappreminder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(help_text='مثال: appointment_date', max_length=50)),
                ('label', models.CharField(help_text='التسمية المعروضة للسكرتيرة، مثال: تاريخ الموعد', max_length=100)),
                ('variable_position', models.PositiveIntegerField(help_text='رقم المتغير في القالب، مثال: 3 يعني {{3}}')),
                ('field_type', models.CharField(choices=[('text', 'نص'), ('date', 'تاريخ'), ('time', 'وقت'), ('number', 'رقم')], default='text', max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True, help_text='هل يستطيع السكرتير تعديل هذا الحقل قبل الإرسال')),
                ('auto_fill_source', models.CharField(blank=True, default='', max_length=100)),
                ('default_value', models.CharField(blank=True, default='', max_length=255)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reminders.remindertemplate')),
            ],
            options={
                'ordering': ['display_order', 'variable_position'],
                'unique_together': {('template', 'variable_position')},
            },
        ),
        migrations.AddIndex(
            model_name='whatsappreminder',
            index=models.Index(fields=['patient', 'reminder_type', 'created_at'], name='reminders_w_patient_1afe84_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappreminder',
            index=models.Index(fields=['status'], name='reminders_w_status_d0e834_idx'),
        ),
    ]
